### ISSUE TITLE
Different bibdaterangeseps in date ranges

### ISSUE THREAD

**Issue by CarlOrff** [CarlOrff/biblatex-archaeology#15]
Should be slash in consecutive years and dash in longer ranges. Same problem as here: https://github.com/LukasCBossert/biblatex-archaeologie/issues/133. Fingers crossed that we can borrow moewew's code.

**Comment by CarlOrff** [comment]
Works perfectly!

**Comment by CarlOrff** [comment]
Grouped `\blx@metadateinfo` as adviced by @moewew in https://github.com/CarlOrff/biblatex-archaeology/commit/d8cedbb8a0a57f237493d5b7e912bc206f177032#commitcomment-28503945

**Comment by CarlOrff** [comment]
Fix `english-archaeology.lbx`  as soon as biblatex 3.12 is out:
https://github.com/LukasCBossert/biblatex-archaeologie/commit/0fafe585a0378c26188f80caa67470803ab1be24
https://github.com/LukasCBossert/biblatex-archaeologie/pull/146

**Comment by moewew** [comment]
It'll probably take some time until `biblatex` 3.12 is released. But the issue is not particularly pressing, I presume.

**Comment by CarlOrff** [comment]
Done: https://github.com/CarlOrff/biblatex-archaeology/commit/a1b4a88a73fd9a353b4e97eb52f8443d45f73f4f
