### ISSUE TITLE
next version of biblatex will drop xstring

### ISSUE THREAD

**Issue by moewew** [CarlOrff/biblatex-archaeology#27]
For the upcoming version we are currently planning on getting rid of `xstring` code in `biblatex`. As a consequence `biblatex` would not require `xstring` any more and would not load the `xstring` package itself any more. `biblatex` styles that need `xstring` would have to load the package explicitly themselves. See https://github.com/plk/biblatex/pull/816 for the current state of affairs.

Your style uses some `xstring` commands, for example `\IfBeginWith` and `\IfInteger`. So to continue working properly, the files that use those commands should load `xstring`.

Even if it turns out that the change can not go through as planned, it is still a very good idea to load `xstring` explicitly if your style needs it.

We are hoping to release a new version of `biblatex` in the not too distant future (I can't promise any ETA as of now, there will be a pre-release announcement on [comp.text.tex](https://groups.google.com/forum/#!forum/comp.text.tex)). You can learn more about the upcoming changes in https://github.com/plk/biblatex/blob/dev/doc/latex/biblatex/CHANGES.md. If you can find time to test your style against the new dev version (https://sourceforge.net/projects/biblatex/files/development/, you'll also need Biber 2.12 from https://sourceforge.net/projects/biblatex-biber/files/biblatex-biber/development/binaries/) feedback would be appreciated.

**Comment by CarlOrff** [comment]
Thanks! Done: https://github.com/CarlOrff/biblatex-archaeology/commit/58bfa3f678fa46b52dacc28df4b527e8fb07fcc8

**Comment by moewew** [comment]
Brilliant. Thank you very much for the swift action.
