### ISSUE TITLE
aefkw style gives missing number error

### ISSUE THREAD

**Issue by u-fischer** [CarlOrff/biblatex-archaeology#29]
~~~~~
\documentclass{article}
\usepackage[T1]{fontenc}
\usepackage[english]{babel}
\usepackage{csquotes}

\usepackage[style=aefkw]{biblatex}
\addbibresource{biblatex-examples.bib}

\begin{document}
\cite{doody}
\printbibliography
\end{document}

~~~~~

gives

~~~~
! Missing number, treated as zero.
<to be read again> 
                   i
l.426 ...l\blx@uniquename\blx@opt@uniquename@false
                                                  
~~~~

in a current texlive 2019

**Comment by moewew** [comment]
The relevant commit in `biblatex` is https://github.com/plk/biblatex/commit/8adf70571cad8349ddcc4e9e966154a3f5b21217.

**Comment by u-fischer** [comment]
The styles `eaz-alt` ,` dguf-alt`, `dguf-apa`, `verbose-archaeology`, `offa` , `authoryear-archaeology` , `rgzm-inline` have the same problem.

**Comment by CarlOrff** [comment]
Thanks for the hint. I'll look at it at the weekend.

**Comment by CarlOrff** [comment]
Fixed ib https://github.com/CarlOrff/biblatex-archaeology/commit/7af1ce8f3603be51abce5b45992efd78c924417b
