### ISSUE TITLE
Overleaf Support

### ISSUE THREAD

**Issue by lomadi** [CarlOrff/biblatex-archaeology#31]
Is it possible to use biblatex-archaeology within Overleaf, if yes some small tutorial would be great, or even an example available within Overleaf

best regards / liebe Grüße
Heimo

**Comment by CarlOrff** [comment]
Is there any special concern with Overleaf? I have tried on a limited free plan, and biblatex-archaeology is there. Couldn't observe any difference to a local install of TEX live in a quick test. As far as I know Overleaf maintains full TeX live releases. What doesn*t work is the rich text converter. But such conversions are a major issue. One of the reasons I missed the deadline for TeX live 2021 with biblatex-archaeology 2.3 is that I am working on smooth conversion to ODT, which can be opened by MS Windows and LibreOffice and saved as DOC(X) or RTF(X).

**Comment by lomadi** [comment]
thanks, for the "super-fast" response, I'm not  an Overleaf / Tex expert, so it is not obvious for me, how to install  biblatex-archaeology within Overleaf. It would be great, if you could share an example project.

**Comment by CarlOrff** [comment]
Appears biblatex-archaeology is available out of box as part of TeX live. See my test document https://www.overleaf.com/read/mjfmmyhfvdrz
