### ISSUE TITLE
Planned change in biblatex v3.17: `\DeclareDelimFormat` no longer supports a list of names

### ISSUE THREAD

**Issue by moewew** [CarlOrff/biblatex-archaeology#32]
As it turns out `biblatex`'s handling of a list of names (the first mandatory argument of `\DeclareDelimFormat`) is slightly broken. The contexts are not updated correctly if a list is used. Since it is unusual for `biblatex` commands to allow a list in this position anyway I'd like to remove the support for lists there and only allow a single name. See https://github.com/plk/biblatex/pull/1161.

This has consequences for this style.
```latex
% \begin{format}{authortypedelim}
% \begin{format}{editortypedelim}
% \begin{format}{translatortypedelim}
% Delimiter between name and its role.
%    \begin{macrocode}
\DeclareDelimFormat{authortypedelim,editortypedelim,translatortypedelim}{\addspace}
%    \end{macrocode}
% \end{format}
% \end{format}
% \end{format}
```
would have to be rewritten.

Either to
```latex
% \begin{format}{authortypedelim}
% \begin{format}{editortypedelim}
% \begin{format}{translatortypedelim}
% Delimiter between name and its role.
%    \begin{macrocode}
\DeclareDelimFormat{authortypedelim}{\addspace}
\DeclareDelimFormat{editortypedelim}{\addspace}
\DeclareDelimFormat{translatortypedelim}{\addspace}
%    \end{macrocode}
% \end{format}
% \end{format}
% \end{format}
```
which would be equivalent to the current situation.

Or to
```latex
% \begin{format}{authortypedelim}
% \begin{format}{editortypedelim}
% \begin{format}{translatortypedelim}
% Delimiter between name and its role.
%    \begin{macrocode}
\DeclareDelimFormat{authortypedelim}{\addspace}
\DeclareDelimAlias{editortypedelim}{authortypedelim}
\DeclareDelimAlias{translatortypedelim}{authortypedelim}
%    \end{macrocode}
% \end{format}
% \end{format}
% \end{format}
```
which uses aliasing.

These two changes will work even before v3.17 is out, so this change would not have to wait for a 3.17 release.

**Comment by moewew** [comment]
I'll keep you in the loop and will comment here once the PR is merged and once 3.17 is out (or scheduled for release).

**Comment by CarlOrff** [comment]
Fixed in https://github.com/CarlOrff/biblatex-archaeology/commit/1b6169709203b15c8bb143f777b41f80b659b079
 Thank you!

**Comment by moewew** [comment]
Just the promised heads-up: `biblatex` 3.17 is being prepared for release and will be sent off to CTAN once all Biber binaries have been built (https://github.com/plk/biblatex/issues/842).
