### ISSUE TITLE
year is ignored

### ISSUE THREAD

**Issue by u-fischer** [CarlOrff/biblatex-archaeology#34]
As biblatex-archaeology resets the labeldate format bib entries which uses `year` instead of `date` get a "nodate" marker:

~~~~
\documentclass{article}
\usepackage[style=authoryear-archaeology]{biblatex}
\addbibresource{biblatex-examples.bib}

%\DeclareLabeldate{%
%    \field{date}
%    \field{year}%<----
%    \field{pubstate}
%    \literal{nodate}
%}

\begin{document}
\cite{doody}
\printbibliography
\end{document}

~~~~

![image](https://user-images.githubusercontent.com/4047173/145619441-4692c91d-d3c0-4a0e-8538-1f174a80d566.png)

(unrelated but the example produce also a few warnings).

**Comment by CarlOrff** [comment]
Thanks for this. Fixed in https://github.com/CarlOrff/biblatex-archaeology/commit/7198ed2079616be65d6173a893dba46da017195f

	\documentclass{article}
	\usepackage[style=authoryear-archaeology]{biblatex}
	\addbibresource{biblatex-examples.bib}

	%\DeclareLabeldate{%
	%    \field{date}
	%    \field{year}%<----
	%    \field{pubstate}
	%    \literal{nodate}
	%}

	\DeclareSourcemap{
		\maps[datatype = bibtex]{
			\map{
				\step[
					notfield=date,
					fieldsource = year, 
					match = \regexp{\A\d{4}\Z},
					fieldtarget = date,
				]
			}
		}
	}
	\begin{document}
	\cite{doody}
	\printbibliography
	\end{document}

**Comment by CarlOrff** [comment]
Added year as labeldate field. After the former commit it can only match if there is something peculiar in it, This should get presented to the user. https://github.com/CarlOrff/biblatex-archaeology/commit/38cc549c524a2a63c0832e9cabc231549ec13005
