### ISSUE TITLE
Upcoming changes in biblatex 3.8: origlanguage becomes a list

### ISSUE THREAD

**Issue by moewew** [CarlOrff/biblatex-archaeology#6]
In the upcoming (and as of now unreleased) version 3.8 of `biblatex` `origlanguage` will change its type from `field` to `list`.

I'm not sure if this style will be affected, but since a grep showed a line containing `origlanguage`, it's better to be safe than sorry.
https://github.com/CarlOrff/biblatex-archaeology/blob/18e4686d2ba6f2e5e545286540c03b99a2e2ce61/biblatex-archaeology.dtx#L7581
Incidentally it looks like you already assumed `origlanguage` was a list.

For background info see https://github.com/plk/biblatex/issues/594

You might also want to have a look at the other changes in 3.8 https://github.com/plk/biblatex/blob/dev/doc/latex/biblatex/CHANGES.org

**Comment by CarlOrff** [comment]
Ok, thanks!
