### ISSUE TITLE
Upcoming changes in biblatex 3.8: extrayear and \DeclareSortingScheme

### ISSUE THREAD

**Issue by moewew** [CarlOrff/biblatex-archaeology#7]
The upcoming version 3.8 of `biblatex` will introduce a few more changes.

- `\DeclareSortingScheme` will be called `\DeclareSortingTemplate`
- `extrayear` becomes `extradate`, macro names that make reference to `extrayear` were also changed.

Backwards compatibility code is in place to allow styles using the old name to continue to work, but it would be appreciated if developers made the transition to the new names.

The full list of changes is at https://github.com/plk/biblatex/blob/dev/doc/latex/biblatex/CHANGES.org and https://github.com/plk/biblatex/wiki. Maybe you can make use of some of the new features.

**Comment by moewew** [comment]
I see that you already implemented the necessary changes in https://github.com/CarlOrff/biblatex-archaeology/commit/01e45370e27370cfa1a85431732a220682a05761

There is just one hold-out of the old naming scheme in line 10228 in the definition of `labeldate+edition` it still says `\usebibmacro{date+extrayear}%`, the new name is `\usebibmacro{date+extradate}%`.

**Comment by CarlOrff** [comment]
Fixed! Thank you very much!
